"""TemplateDef · Demanda Ordinaria Laboral de Primera Instancia."""
from lex.templates.base import (
    DetailProfile, ForensicStructure, HunterQuery, Rule, SectionDef, TemplateDef,
)

TEMPLATE = TemplateDef(
    id="demanda_laboral_ordinaria",
    nombre="Demanda Ordinaria Laboral",
    jurisdiccion="laboral",
    materia="despido sin justa causa y reclamación de prestaciones sociales",
    description="Demanda Ordinaria Laboral de Primera Instancia (Art. 1 Ley 712/01)",
    sections_plan=[
        SectionDef("encabezado", "Encabezado y referencia", 1, roman=None,
                   expected_blocks=["paragraph"]),
        SectionDef("partes", "PARTES DEL PROCESO", 2, roman="I",
                   expected_blocks=["subsection", "paragraph"]),
        SectionDef("competencia", "JURISDICCIÓN, COMPETENCIA Y CUANTÍA", 3, roman="II",
                   expected_blocks=["paragraph"]),
        SectionDef("hechos", "HECHOS", 4, roman="III",
                   expected_blocks=["paragraph", "hecho"],
                   section_instruction="Genera 12-18 hechos numerados con fechas y montos concretos."),
        SectionDef("pretensiones", "PRETENSIONES", 5, roman="IV",
                   expected_blocks=["subsection", "pretension"],
                   section_instruction="Genera 8-13 pretensiones en numeración romana: separar declarativas y de condena."),
        SectionDef("fundamentos_derecho", "FUNDAMENTOS DE DERECHO", 6, roman="V",
                   expected_blocks=["subsection", "paragraph", "norma_citada", "jurisprudencia"],
                   section_instruction="Cita textual normas + jurisprudencia con M.P. en bloques 'jurisprudencia'."),
        SectionDef("razonamiento", "RAZONAMIENTO JURÍDICO", 7, roman="VI",
                   expected_blocks=["paragraph", "silogismo"],
                   section_instruction="Emite al menos un bloque tipo 'silogismo' con Premisa Mayor/Menor/Conclusión."),
        SectionDef("liquidacion", "LIQUIDACIÓN DE LAS PRETENSIONES", 8, roman="VII",
                   expected_blocks=["paragraph", "calc_step", "table"],
                   section_instruction="Para cada concepto laboral, un bloque 'calc_step' (fórmula + aplicación + total). Termina con un bloque 'table' resumen con shading."),
        SectionDef("pruebas", "PRUEBAS", 9, roman="VIII",
                   expected_blocks=["subsection", "list_item"]),
        SectionDef("anexos", "ANEXOS", 10, roman="IX",
                   expected_blocks=["list_item"]),
        SectionDef("notificaciones", "NOTIFICACIONES", 11, roman="X",
                   expected_blocks=["subsection", "paragraph"]),
        SectionDef("juramento", "JURAMENTO", 12, roman=None,
                   expected_blocks=["juramento"]),
        SectionDef("firma", "Firma", 13, roman=None,
                   expected_blocks=["firma"]),
    ],
    hunters=[
        HunterQuery("Art. 64 CST indemnización despido sin justa causa", "sala_laboral_csj", top_k=3),
        HunterQuery("Art. 65 CST sanción moratoria buena fe empleador", "sala_laboral_csj", top_k=3),
        HunterQuery("Art. 99 Ley 50/90 cesantías no consignación oportuna", "corte_constitucional", top_k=2),
        HunterQuery("contrato realidad subordinación Art. 23 CST", "sala_laboral_csj", top_k=2),
        HunterQuery("texto literal Art. 64 CST modificado Ley 789/02", "normas_codigos", top_k=2),
    ],
    validation_rules=[
        Rule.has_section("partes"),
        Rule.has_section("hechos"),
        Rule.has_section("pretensiones"),
        Rule.has_section("liquidacion"),
        Rule.min_hechos(10),
        Rule.min_pretensiones(6),
        Rule.cita_minimo(["Art. 64", "Art. 65", "CST"]),
    ],
    detail_profile=DetailProfile(
        min_paragraphs_per_section=4,
        min_hechos=12,
        min_pretensiones=8,
        require_silogismo=True,
        require_calculos=True,
        require_juramento=True,
        require_pretensiones_romanas=True,
        require_table_resumen=True,
        jurisprudencia_min=3,
        normas_min=6,
        tone="solemne_forense",
    ),
    forensic_structure=ForensicStructure(
        style="demanda", pretensiones_label="PRIMERA",
        show_juramento_section=True, show_firma_section=True,
    ),
    required_data={
        "demandante_nombre": "str",
        "demandante_cc": "str",
        "demandada_razon_social": "str",
        "demandada_nit": "str",
        "salario_mensual": "number",
        "fecha_ingreso": "date YYYY-MM-DD",
        "fecha_despido": "date YYYY-MM-DD",
        "cargo": "str",
        "ciudad": "str",
    },
    calculadora="lex.calc.laboral:full_liquidacion",  # M3 lo implementa
)
