-- ============================================================
-- LexAI · Sprint M19.24.E.1 · Recipes Anchor Pre-cargados
-- Migration date: 2026-06-01
-- Idempotente · additive · no breaking changes
-- ============================================================
--
-- Pre-carga structure_recipes con 70+ doc_types colombianos
-- curados manualmente con los campos M19.24 completos.
-- Esto garantiza calidad alta desde el día 1 sin esperar al cache LLM.
--
-- Cada recipe contiene:
--   - structure_key normalizada
--   - sections_plan (lista de secciones)
--   - playbooks (instrucciones por seccion para el block_generator universal)
--   - document_family, regimen_aplicable, naturaleza_acto
--   - encabezado_tipo, cierre_tipo, numeracion_estilo
--   - requires_pretensiones / requires_hechos / requires_juramento
--
-- ON CONFLICT DO NOTHING: si ya existe un recipe (cached por structure_discovery),
-- no lo sobreescribe — preserva ajustes previos.

INSERT INTO structure_recipes (
  structure_key, doc_type, jurisdiccion, document_family, regimen_aplicable,
  naturaleza_acto, encabezado_tipo, cierre_tipo, numeracion_estilo,
  requires_pretensiones, requires_hechos, requires_juramento,
  sections_plan, playbooks, norma_procesal_ref, juramento_norma_ref,
  juez_competente, cuerpos_normativos_minimos, generated_by
) VALUES

-- ============================================================
-- NOTARIAL — PODERES (5 tipos)
-- ============================================================
('poder_especial:notarial:_:persona_natural', 'poder_especial', 'notarial',
 'notarial_poder', 'notarial_extrajudicial', 'de_mandato',
 'memorial_notario', 'firma_partes_notarial+diligencia_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"comparecencia","title":"Comparecencia del Poderdante","order":2,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"apoderado","title":"Designación del Apoderado","order":3,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"objeto","title":"PRIMERA. Objeto del Poder","order":4,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"facultades","title":"Facultades Especiales","order":5,"roman":null,"expected_blocks":["paragraph","list_item"]},
   {"key":"naturaleza","title":"Naturaleza y Fundamento","order":6,"roman":null,"expected_blocks":["paragraph","norma_citada"]},
   {"key":"vigencia","title":"Vigencia y Revocabilidad","order":7,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"aceptacion","title":"Aceptación del Apoderado","order":8,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"firma","title":"Lugar, Fecha y Firmas","order":9,"roman":null,"expected_blocks":["firma"]},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":10,"roman":null,"expected_blocks":["paragraph"]}
 ]'::jsonb,
 '{
   "encabezado": ["Dirige el documento al Señor(a) Notario(a) del Círculo correspondiente con la dirección E.S.D.", "Indica el título PODER ESPECIAL centrado en negrita"],
   "comparecencia": ["Identifica al poderdante con fórmula Yo, NOMBRE, mayor de edad, vecino de CIUDAD, identificado con cédula CC, obrando en mi calidad de X", "Si es representante legal, agrega razón social + NIT + matrícula mercantil + Cámara de Comercio"],
   "apoderado": ["Identifica al apoderado con fórmula similar", "Incluye profesión, T.P. si aplica, dirección y correo electrónico"],
   "objeto": ["Declara expresamente que confiere PODER ESPECIAL, AMPLIO Y SUFICIENTE", "Aclara que las facultades son CLARAS, EXPRESAS Y ESPECÍFICAS (no extensivas ni analógicas)"],
   "facultades": ["Enumera cada facultad como cláusula independiente: SEGUNDA, TERCERA, CUARTA", "Cada cláusula con título descriptivo en negrita", "Para facultades de disposición incluye explícitamente tope máximo de cuantía", "Si compromete inmuebles, prevé expresamente concurrir a escritura pública"],
   "naturaleza": ["Aclara que es mandato con representación de carácter extrajudicial", "Cita arts. 2142 y ss. CC + normas pertinentes CCo", "Indica que se autenticará conforme al Decreto 960/1970", "NO cita CGP (es para poderes judiciales)"],
   "vigencia": ["Define plazo de vigencia (placeholder o cifra)", "Cláusula expresa de revocabilidad sin necesidad de causa"],
   "aceptacion": ["El apoderado declara ACEPTA en mayúsculas", "Se obliga a ejercerlo con diligencia dentro del marco autorizado"],
   "firma": ["Bloque firma con cierre_tipo=firma_partes_notarial: dos firmas separadas - EL PODERDANTE y EL APODERADO (ACEPTO)", "Bajo cada firma: nombre completo, CC + lugar expedición", "Bajo el poderdante también: cargo/calidad de representante legal si aplica"],
   "diligencia_notarial": ["Bloque dedicado para la Notaría", "Indica espacio reservado para nota de presentación personal y reconocimiento de contenido", "Fecha y Escritura/Acta No. para que el notario llene"]
 }'::jsonb,
 'Arts. 2142 ss. Código Civil + Decreto 960/1970 (Estatuto Notarial)',
 NULL,
 NULL,
 '["CC","CCo","Decreto 960/1970"]'::jsonb, 'manual_seed_m19_24'),

('poder_general:notarial:_:persona_natural', 'poder_general', 'notarial',
 'notarial_poder', 'notarial_extrajudicial', 'de_mandato',
 'memorial_notario', 'firma_partes_notarial+diligencia_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"comparecencia","title":"Comparecencia","order":2,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"apoderado","title":"Designación del Apoderado","order":3,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"facultades_administracion","title":"PRIMERA. Facultades de Administración","order":4,"roman":null,"expected_blocks":["paragraph","list_item"]},
   {"key":"limitaciones","title":"SEGUNDA. Limitaciones del Poder","order":5,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"vigencia","title":"Vigencia","order":6,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"aceptacion","title":"Aceptación","order":7,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"firma","title":"Firmas","order":8,"roman":null,"expected_blocks":["firma"]},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":9,"roman":null,"expected_blocks":["paragraph"]}
 ]'::jsonb,
 '{
   "encabezado":["Título PODER GENERAL centrado", "Saludo al notario E.S.D."],
   "comparecencia":["Identificación completa del poderdante (CC, domicilio)"],
   "apoderado":["Identificación completa del apoderado"],
   "facultades_administracion":["Enuncia que confiere poder general para administración (no disposición salvo autorización expresa)", "Lista facultades típicas: representar en negocios, manejar cuentas, cobrar y pagar, contratar servicios"],
   "limitaciones":["Aclara expresamente que NO autoriza enajenar bienes raíces ni constituir garantías reales sin autorización adicional", "Esto preserva al poderdante de actos de disposición no consentidos"],
   "vigencia":["Define plazo y revocabilidad expresa"],
   "aceptacion":["Apoderado declara ACEPTA"],
   "firma":["cierre_tipo=firma_partes_notarial"],
   "diligencia_notarial":["Espacio para nota notarial"]
 }'::jsonb,
 'Arts. 2156-2160 CC + Decreto 960/1970',
 NULL, NULL,
 '["CC","Decreto 960/1970"]'::jsonb, 'manual_seed_m19_24'),

('poder_judicial:judicial:_:persona_natural', 'poder_judicial', 'judicial',
 'notarial_poder', 'procesal_judicial', 'de_mandato',
 'memorial_juzgado', 'firma_partes_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"poderdante","title":"Identificación del Poderdante","order":2,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"abogado","title":"Identificación del Abogado","order":3,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"facultades","title":"Facultades para Actuación Judicial","order":4,"roman":null,"expected_blocks":["paragraph","list_item"]},
   {"key":"facultades_especiales","title":"Facultades Especiales (Art. 77 CGP)","order":5,"roman":null,"expected_blocks":["paragraph","list_item"]},
   {"key":"sustitucion","title":"Facultad de Sustitución","order":6,"roman":null,"expected_blocks":["paragraph"]},
   {"key":"firma","title":"Firmas","order":7,"roman":null,"expected_blocks":["firma"]}
 ]'::jsonb,
 '{
   "encabezado":["Título PODER ESPECIAL JUDICIAL", "Dirigido al Juez de la jurisdicción competente"],
   "poderdante":["Datos completos del poderdante (CC, dirección notificación, correo)"],
   "abogado":["Datos completos del abogado: nombre, T.P. del C.S.J., dirección profesional, correo"],
   "facultades":["Confiere poder para representación en proceso específico (identificar tipo de proceso, partes, juzgado si conocido)"],
   "facultades_especiales":["Si se requieren facultades especiales del Art. 77 CGP, listarlas expresamente: confesar, recibir, transigir, desistir, etc.", "Sin enumeración expresa, las facultades especiales no se entienden conferidas"],
   "sustitucion":["Define si autoriza sustitución del poder"],
   "firma":["cierre_tipo=firma_partes_notarial"]
 }'::jsonb,
 'Arts. 74-77 CGP',
 NULL,
 'Juez competente del proceso',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('sustitucion_poder:judicial:_:persona_natural', 'sustitucion_poder', 'judicial',
 'notarial_poder', 'procesal_judicial', 'de_mandato',
 'memorial_juzgado', 'firma_partes_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_poder_original","title":"Identificación del Poder Original","order":2},
   {"key":"sustituyente","title":"Apoderado Sustituyente","order":3},
   {"key":"sustituto","title":"Apoderado Sustituto","order":4},
   {"key":"alcance_sustitucion","title":"Alcance de la Sustitución","order":5},
   {"key":"firma","title":"Firmas","order":6}
 ]'::jsonb,
 '{
   "encabezado":["Título SUSTITUCIÓN DE PODER"],
   "identificacion_poder_original":["Datos del poder que se sustituye: fecha, notaría, escritura/acta"],
   "sustituyente":["Apoderado original que sustituye"],
   "sustituto":["Nuevo apoderado a quien se transfiere el poder"],
   "alcance_sustitucion":["Total o parcial; con facultades plenas o limitadas"],
   "firma":["cierre_tipo=firma_partes_notarial"]
 }'::jsonb,
 'Art. 2161 CC + Art. 75 CGP',
 NULL, NULL,
 '["CC","CGP"]'::jsonb, 'manual_seed_m19_24'),

('revocatoria_poder:notarial:_:persona_natural', 'revocatoria_poder', 'notarial',
 'notarial_poder', 'notarial_extrajudicial', 'extintivo',
 'memorial_notario', 'firma_natural+diligencia_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_poderdante","title":"Identificación del Poderdante","order":2},
   {"key":"identificacion_poder","title":"Identificación del Poder a Revocar","order":3},
   {"key":"manifestacion_revocatoria","title":"Manifestación de Revocatoria","order":4},
   {"key":"notificacion_apoderado","title":"Notificación al Apoderado","order":5},
   {"key":"firma","title":"Firma","order":6},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":7}
 ]'::jsonb,
 '{
   "encabezado":["Título REVOCATORIA DE PODER"],
   "identificacion_poderdante":["Datos del poderdante que revoca"],
   "identificacion_poder":["Datos exactos del poder revocado: fecha, notaría, escritura/acta, apoderado"],
   "manifestacion_revocatoria":["Declara expresamente revocar el poder en su totalidad", "Indica fecha desde la cual deja de tener vigencia"],
   "notificacion_apoderado":["Indica que se notificará al apoderado", "Y a las entidades donde se haya hecho valer el poder"],
   "firma":["cierre_tipo=firma_natural"],
   "diligencia_notarial":["Espacio para nota notarial"]
 }'::jsonb,
 'Arts. 2189-2191 CC + Decreto 960/1970',
 NULL, NULL,
 '["CC","Decreto 960/1970"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- NOTARIAL — DECLARACIONES (3 tipos)
-- ============================================================
('declaracion_extrajuicio:notarial:_:persona_natural', 'declaracion_extrajuicio', 'notarial',
 'notarial_extrajuicio', 'notarial_extrajudicial', 'declarativo',
 'memorial_notario', 'firma_natural+diligencia_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"declarante","title":"Identificación del Declarante","order":2},
   {"key":"objeto_declaracion","title":"Objeto de la Declaración","order":3},
   {"key":"hechos_declarados","title":"Hechos Declarados","order":4},
   {"key":"manifestacion_juramentada","title":"Manifestación bajo Juramento","order":5},
   {"key":"firma","title":"Firma","order":6},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":7}
 ]'::jsonb,
 '{
   "encabezado":["Título DECLARACIÓN EXTRAJUICIO BAJO JURAMENTO"],
   "declarante":["Datos completos del declarante"],
   "objeto_declaracion":["Para qué se hace: trámite específico, entidad destinataria"],
   "hechos_declarados":["Enumera los hechos en cláusulas numeradas (PRIMERA, SEGUNDA, TERCERA)", "Cada hecho declarativo con detalle suficiente"],
   "manifestacion_juramentada":["Declara bajo gravedad de juramento que los hechos son ciertos", "Cita Art. 442 CP (falso testimonio)"],
   "firma":["cierre_tipo=firma_natural"],
   "diligencia_notarial":["Espacio para que el notario reciba la declaración bajo juramento"]
 }'::jsonb,
 'Art. 7 Decreto 960/1970 + Art. 442 CP',
 NULL, NULL,
 '["Decreto 960/1970","CP"]'::jsonb, 'manual_seed_m19_24'),

('autenticacion_documento:notarial:_:persona_natural', 'autenticacion_documento', 'notarial',
 'notarial_extrajuicio', 'notarial_extrajudicial', 'informativo',
 'memorial_notario', 'firma_natural+diligencia_notarial', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"presentante","title":"Presentante","order":2},
   {"key":"documento_a_autenticar","title":"Identificación del Documento","order":3},
   {"key":"contenido_documento","title":"Contenido","order":4},
   {"key":"firma","title":"Firma","order":5},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":6}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 73 Decreto 960/1970',
 NULL, NULL,
 '["Decreto 960/1970"]'::jsonb, 'manual_seed_m19_24'),

('reconocimiento_firma:notarial:_:persona_natural', 'reconocimiento_firma', 'notarial',
 'notarial_extrajuicio', 'notarial_extrajudicial', 'informativo',
 'memorial_notario', 'firma_natural+diligencia_notarial', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"otorgante","title":"Otorgante","order":2},
   {"key":"documento","title":"Documento cuya Firma se Reconoce","order":3},
   {"key":"manifestacion","title":"Manifestación de Reconocimiento","order":4},
   {"key":"firma","title":"Firma","order":5},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":6}
 ]'::jsonb,
 '{}'::jsonb,
 'Decreto 960/1970',
 NULL, NULL,
 '["Decreto 960/1970"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- JUDICIAL — DEMANDAS CIVILES (5 tipos)
-- ============================================================
('demanda_civil_ordinaria:civil:mayor:persona_natural', 'demanda_civil_ordinaria', 'civil',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"pretensiones","title":"Pretensiones","order":4,"roman":"III"},
   {"key":"fundamentos","title":"Fundamentos de Derecho","order":5,"roman":"IV"},
   {"key":"competencia_cuantia","title":"Competencia y Cuantía","order":6,"roman":"V"},
   {"key":"pruebas","title":"Pruebas","order":7,"roman":"VI"},
   {"key":"anexos","title":"Anexos","order":8,"roman":"VII"},
   {"key":"notificaciones","title":"Notificaciones","order":9,"roman":"VIII"},
   {"key":"juramento","title":"Juramento Estimatorio","order":10,"roman":"IX"},
   {"key":"firma","title":"Firma","order":11,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 82-90 CGP',
 'Art. 206 CGP (Ley 1564/2012)',
 'Juez Civil del Circuito',
 '["CGP","CC"]'::jsonb, 'manual_seed_m19_24'),

('demanda_civil_verbal:civil:menor:persona_natural', 'demanda_civil_verbal', 'civil',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"pretensiones","title":"Pretensiones","order":4,"roman":"III"},
   {"key":"fundamentos","title":"Fundamentos de Derecho","order":5,"roman":"IV"},
   {"key":"competencia_cuantia","title":"Competencia y Cuantía","order":6,"roman":"V"},
   {"key":"pruebas","title":"Pruebas","order":7,"roman":"VI"},
   {"key":"anexos","title":"Anexos","order":8,"roman":"VII"},
   {"key":"notificaciones","title":"Notificaciones","order":9,"roman":"VIII"},
   {"key":"juramento","title":"Juramento Estimatorio","order":10,"roman":"IX"},
   {"key":"firma","title":"Firma","order":11,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 368-393 CGP',
 'Art. 206 CGP',
 'Juez Civil Municipal',
 '["CGP","CC"]'::jsonb, 'manual_seed_m19_24'),

('demanda_ejecutivo_singular:civil:_:persona_natural', 'demanda_ejecutivo_singular', 'civil',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"titulo_ejecutivo","title":"Título Ejecutivo","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Mandamiento de Pago","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos de Derecho","order":6,"roman":"V"},
   {"key":"medidas_cautelares","title":"Medidas Cautelares","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"notificaciones","title":"Notificaciones","order":10,"roman":"IX"},
   {"key":"juramento","title":"Juramento Estimatorio","order":11,"roman":"X"},
   {"key":"firma","title":"Firma","order":12,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 422-447 CGP',
 'Art. 206 CGP',
 'Juez Civil del Circuito',
 '["CGP","CC"]'::jsonb, 'manual_seed_m19_24'),

('demanda_pertenencia:civil:mayor:persona_natural', 'demanda_pertenencia', 'civil',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"identificacion_inmueble","title":"Identificación del Inmueble","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos de Derecho","order":6,"roman":"V"},
   {"key":"competencia","title":"Competencia","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"emplazamiento","title":"Emplazamiento de Terceros","order":10,"roman":"IX"},
   {"key":"juramento","title":"Juramento Estimatorio","order":11,"roman":"X"},
   {"key":"firma","title":"Firma","order":12,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 375 CGP',
 'Art. 206 CGP',
 'Juez Civil del Circuito',
 '["CGP","CC"]'::jsonb, 'manual_seed_m19_24'),

('demanda_responsabilidad_civil:civil:mayor:persona_natural', 'demanda_responsabilidad_civil', 'civil',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"dano_y_nexo","title":"Daño y Nexo Causal","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"liquidacion","title":"Liquidación de Perjuicios","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos de Derecho","order":7,"roman":"VI"},
   {"key":"competencia_cuantia","title":"Competencia y Cuantía","order":8,"roman":"VII"},
   {"key":"pruebas","title":"Pruebas","order":9,"roman":"VIII"},
   {"key":"anexos","title":"Anexos","order":10,"roman":"IX"},
   {"key":"juramento","title":"Juramento Estimatorio","order":11,"roman":"X"},
   {"key":"firma","title":"Firma","order":12,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 2341 CC + 82-90 CGP',
 'Art. 206 CGP',
 'Juez Civil del Circuito',
 '["CGP","CC"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- JUDICIAL — DEMANDAS FAMILIA (5 tipos)
-- ============================================================
('demanda_divorcio:familia:_:persona_natural', 'demanda_divorcio', 'familia',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"matrimonio","title":"Matrimonio","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"causal","title":"Causal Invocada","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"hijos_menores","title":"Datos de Hijos Menores","order":7,"roman":"VI"},
   {"key":"regulacion_alimentos","title":"Régimen de Alimentos","order":8,"roman":"VII"},
   {"key":"custodia_visitas","title":"Custodia y Visitas","order":9,"roman":"VIII"},
   {"key":"fundamentos","title":"Fundamentos","order":10,"roman":"IX"},
   {"key":"competencia","title":"Competencia","order":11,"roman":"X"},
   {"key":"pruebas","title":"Pruebas","order":12,"roman":"XI"},
   {"key":"anexos","title":"Anexos","order":13,"roman":"XII"},
   {"key":"juramento","title":"Juramento Estimatorio","order":14,"roman":"XIII"},
   {"key":"firma","title":"Firma","order":15,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 154-159 CC + 388-389 CGP',
 'Art. 206 CGP',
 'Juez de Familia del Circuito',
 '["CGP","CC","Ley 1098/2006"]'::jsonb, 'manual_seed_m19_24'),

('demanda_alimentos:familia:_:persona_natural', 'demanda_alimentos', 'familia',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"vinculo","title":"Vínculo Familiar","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"capacidad_economica","title":"Capacidad Económica del Alimentante","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos","order":7,"roman":"VI"},
   {"key":"competencia","title":"Competencia","order":8,"roman":"VII"},
   {"key":"pruebas","title":"Pruebas","order":9,"roman":"VIII"},
   {"key":"anexos","title":"Anexos","order":10,"roman":"IX"},
   {"key":"juramento","title":"Juramento Estimatorio","order":11,"roman":"X"},
   {"key":"firma","title":"Firma","order":12,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 411-425 CC + 397-399 CGP',
 'Art. 206 CGP',
 'Juez de Familia',
 '["CGP","CC","Ley 1098/2006"]'::jsonb, 'manual_seed_m19_24'),

('demanda_custodia:familia:_:persona_natural', 'demanda_custodia', 'familia',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"datos_menores","title":"Datos de los Menores","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"interes_superior","title":"Interés Superior del Menor","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"juramento","title":"Juramento","order":10,"roman":"IX"},
   {"key":"firma","title":"Firma","order":11,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 23 + 254 Ley 1098/2006',
 'Art. 206 CGP',
 'Juez de Familia',
 '["CGP","CC","Ley 1098/2006","CN"]'::jsonb, 'manual_seed_m19_24'),

('demanda_filiacion:familia:_:persona_natural', 'demanda_filiacion', 'familia',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"pretensiones","title":"Pretensiones","order":4,"roman":"III"},
   {"key":"fundamentos","title":"Fundamentos","order":5,"roman":"IV"},
   {"key":"prueba_genetica","title":"Solicitud de Prueba Genética","order":6,"roman":"V"},
   {"key":"pruebas","title":"Pruebas","order":7,"roman":"VI"},
   {"key":"anexos","title":"Anexos","order":8,"roman":"VII"},
   {"key":"juramento","title":"Juramento","order":9,"roman":"VIII"},
   {"key":"firma","title":"Firma","order":10,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Ley 721/2001 + Arts. 213-280 CC',
 'Art. 206 CGP',
 'Juez de Familia',
 '["CGP","CC","Ley 721/2001"]'::jsonb, 'manual_seed_m19_24'),

('demanda_impugnacion_paternidad:familia:_:persona_natural', 'demanda_impugnacion_paternidad', 'familia',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"pretensiones","title":"Pretensiones","order":4,"roman":"III"},
   {"key":"fundamentos","title":"Fundamentos","order":5,"roman":"IV"},
   {"key":"pruebas","title":"Pruebas","order":6,"roman":"V"},
   {"key":"anexos","title":"Anexos","order":7,"roman":"VI"},
   {"key":"juramento","title":"Juramento","order":8,"roman":"VII"},
   {"key":"firma","title":"Firma","order":9,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 217-220 CC',
 'Art. 206 CGP',
 'Juez de Familia',
 '["CGP","CC","Ley 1060/2006"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- JUDICIAL — DEMANDAS LABORALES (3 tipos)
-- ============================================================
('demanda_laboral_ordinaria:laboral:mayor:persona_juridica', 'demanda_laboral_ordinaria', 'laboral',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"pretensiones","title":"Pretensiones","order":4,"roman":"III"},
   {"key":"liquidacion","title":"Liquidación de Prestaciones","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos","order":6,"roman":"V"},
   {"key":"competencia","title":"Competencia","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"notificaciones","title":"Notificaciones","order":10,"roman":"IX"},
   {"key":"juramento","title":"Juramento Estimatorio","order":11,"roman":"X"},
   {"key":"firma","title":"Firma","order":12,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'CST + Arts. 25-38 CPTSS',
 'Art. 28 CPTSS',
 'Juez Laboral del Circuito',
 '["CST","CPTSS"]'::jsonb, 'manual_seed_m19_24'),

('demanda_laboral_fuero_sindical:laboral:_:persona_juridica', 'demanda_laboral_fuero_sindical', 'laboral',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"fuero_sindical","title":"Acreditación del Fuero","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos","order":6,"roman":"V"},
   {"key":"competencia","title":"Competencia","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"juramento","title":"Juramento","order":10,"roman":"IX"},
   {"key":"firma","title":"Firma","order":11,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 405-413 CST + 113-118 CPTSS',
 'Art. 28 CPTSS',
 'Juez Laboral del Circuito',
 '["CST","CPTSS"]'::jsonb, 'manual_seed_m19_24'),

('demanda_laboral_reintegro:laboral:_:persona_juridica', 'demanda_laboral_reintegro', 'laboral',
 'judicial_demanda', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"causal_proteccion","title":"Causal de Protección Especial","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"liquidacion","title":"Liquidación Salarios Caídos","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"juramento","title":"Juramento","order":10,"roman":"IX"},
   {"key":"firma","title":"Firma","order":11,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'CST + Ley 361/1997 + SU-049/2017',
 'Art. 28 CPTSS',
 'Juez Laboral del Circuito',
 '["CST","CPTSS","Ley 361/1997"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- JUDICIAL — ADMINISTRATIVAS (3 tipos)
-- ============================================================
('demanda_nulidad_restablecimiento:admin:_:entidad_publica', 'demanda_nulidad_restablecimiento', 'admin',
 'judicial_demanda', 'administrativo_publico', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"acto_administrativo","title":"Acto Administrativo Demandado","order":3,"roman":"II"},
   {"key":"agotamiento_via","title":"Agotamiento de Vía Gubernativa","order":4,"roman":"III"},
   {"key":"hechos","title":"Hechos","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"causales_nulidad","title":"Causales de Nulidad","order":7,"roman":"VI"},
   {"key":"fundamentos","title":"Fundamentos","order":8,"roman":"VII"},
   {"key":"competencia","title":"Competencia","order":9,"roman":"VIII"},
   {"key":"pruebas","title":"Pruebas","order":10,"roman":"IX"},
   {"key":"anexos","title":"Anexos","order":11,"roman":"X"},
   {"key":"juramento","title":"Juramento","order":12,"roman":"XI"},
   {"key":"firma","title":"Firma","order":13,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 137-138 + 162 CPACA',
 'Art. 167 CPACA',
 'Juez/Tribunal Administrativo',
 '["CPACA","CN"]'::jsonb, 'manual_seed_m19_24'),

('demanda_reparacion_directa:admin:_:entidad_publica', 'demanda_reparacion_directa', 'admin',
 'judicial_demanda', 'administrativo_publico', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"dano_antijuridico","title":"Daño Antijurídico","order":4,"roman":"III"},
   {"key":"imputacion","title":"Imputación al Estado","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"liquidacion","title":"Liquidación de Perjuicios","order":7,"roman":"VI"},
   {"key":"fundamentos","title":"Fundamentos","order":8,"roman":"VII"},
   {"key":"competencia","title":"Competencia","order":9,"roman":"VIII"},
   {"key":"pruebas","title":"Pruebas","order":10,"roman":"IX"},
   {"key":"anexos","title":"Anexos","order":11,"roman":"X"},
   {"key":"juramento","title":"Juramento","order":12,"roman":"XI"},
   {"key":"firma","title":"Firma","order":13,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 140 CPACA + 90 CN',
 'Art. 167 CPACA',
 'Juez/Tribunal Administrativo',
 '["CPACA","CN"]'::jsonb, 'manual_seed_m19_24'),

('demanda_contractual_admin:admin:_:entidad_publica', 'demanda_contractual_admin', 'admin',
 'judicial_demanda', 'administrativo_publico', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"contrato","title":"Identificación del Contrato Estatal","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"liquidacion","title":"Liquidación de Perjuicios","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos","order":7,"roman":"VI"},
   {"key":"competencia","title":"Competencia","order":8,"roman":"VII"},
   {"key":"pruebas","title":"Pruebas","order":9,"roman":"VIII"},
   {"key":"anexos","title":"Anexos","order":10,"roman":"IX"},
   {"key":"juramento","title":"Juramento","order":11,"roman":"X"},
   {"key":"firma","title":"Firma","order":12,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 141 CPACA + Ley 80/1993',
 'Art. 167 CPACA',
 'Tribunal Administrativo',
 '["CPACA","Ley 80/1993","CN"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- ACCIONES CONSTITUCIONALES (4 tipos)
-- ============================================================
('tutela:constitucional:_:_', 'tutela', 'constitucional',
 'judicial_constitucional', 'constitucional', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"derechos_vulnerados","title":"Derechos Fundamentales Vulnerados","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"subsidiariedad","title":"Subsidiariedad e Inmediatez","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"notificaciones","title":"Notificaciones","order":9,"roman":"VIII"},
   {"key":"firma","title":"Firma","order":10,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 86 CN + Decreto 2591/1991',
 NULL,
 'Cualquier juez (reparto)',
 '["CN","Decreto 2591/1991"]'::jsonb, 'manual_seed_m19_24'),

('habeas_corpus:constitucional:_:_', 'habeas_corpus', 'constitucional',
 'judicial_constitucional', 'constitucional', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"libertad_vulnerada","title":"Libertad Vulnerada","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 30 CN + Ley 1095/2006',
 NULL,
 'Cualquier juez',
 '["CN","Ley 1095/2006"]'::jsonb, 'manual_seed_m19_24'),

('habeas_data:constitucional:_:persona_juridica', 'habeas_data', 'constitucional',
 'judicial_constitucional', 'constitucional', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"violacion_derecho","title":"Violación al Derecho","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos","order":6,"roman":"V"},
   {"key":"pruebas","title":"Pruebas","order":7,"roman":"VI"},
   {"key":"firma","title":"Firma","order":8,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 15 CN + Ley 1581/2012',
 NULL,
 'Cualquier juez (tutela)',
 '["CN","Ley 1581/2012"]'::jsonb, 'manual_seed_m19_24'),

('accion_popular:constitucional:_:_', 'accion_popular', 'constitucional',
 'judicial_constitucional', 'constitucional', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1,"roman":null},
   {"key":"partes","title":"Partes","order":2,"roman":"I"},
   {"key":"derechos_colectivos","title":"Derechos Colectivos","order":3,"roman":"II"},
   {"key":"hechos","title":"Hechos","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"fundamentos","title":"Fundamentos","order":6,"roman":"V"},
   {"key":"pruebas","title":"Pruebas","order":7,"roman":"VI"},
   {"key":"juramento","title":"Juramento","order":8,"roman":"VII"},
   {"key":"firma","title":"Firma","order":9,"roman":null}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 88 CN + Ley 472/1998',
 'Art. 18 Ley 472/1998',
 'Juez Civil del Circuito o Administrativo según el caso',
 '["CN","Ley 472/1998"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- DENUNCIAS PENALES (2 tipos)
-- ============================================================
('denuncia_penal:penal:_:persona_natural', 'denuncia_penal', 'penal',
 'criminal_denuncia', 'penal_acusatorio', 'petitorio',
 'memorial_autoridad_admin', 'firma_natural', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"denunciante","title":"Datos del Denunciante","order":2},
   {"key":"denunciado","title":"Datos del Denunciado","order":3},
   {"key":"hechos","title":"Relato de los Hechos","order":4},
   {"key":"delito","title":"Posible Tipificación","order":5},
   {"key":"pruebas","title":"Pruebas y Testigos","order":6},
   {"key":"manifestacion_juramentada","title":"Manifestación bajo Gravedad de Juramento","order":7},
   {"key":"firma","title":"Firma","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 66 CPP',
 'Art. 269 CPP',
 'Fiscalía General de la Nación',
 '["CPP","CP"]'::jsonb, 'manual_seed_m19_24'),

('querella_penal:penal:_:persona_natural', 'querella_penal', 'penal',
 'criminal_denuncia', 'penal_acusatorio', 'petitorio',
 'memorial_autoridad_admin', 'firma_natural', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"querellante","title":"Querellante","order":2},
   {"key":"querellado","title":"Querellado","order":3},
   {"key":"hechos","title":"Hechos","order":4},
   {"key":"delito_querellable","title":"Identificación del Delito Querellable","order":5},
   {"key":"pruebas","title":"Pruebas","order":6},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 67-77 CPP + Art. 74 CP',
 'Art. 269 CPP',
 'Fiscalía',
 '["CPP","CP"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- RECURSOS (4 tipos)
-- ============================================================
('recurso_reposicion:judicial:_:_', 'recurso_reposicion', 'civil',
 'judicial_recurso', 'procesal_judicial', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Identificación del Proceso","order":2,"roman":"I"},
   {"key":"providencia_recurrida","title":"Providencia Recurrida","order":3,"roman":"II"},
   {"key":"sustentacion","title":"Sustentación del Recurso","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones del Recurso","order":5,"roman":"IV"},
   {"key":"firma","title":"Firma","order":6}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 318-319 CGP',
 NULL,
 'Mismo juez que dictó la providencia',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('recurso_apelacion:judicial:_:_', 'recurso_apelacion', 'civil',
 'judicial_recurso', 'procesal_judicial', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Proceso","order":2,"roman":"I"},
   {"key":"providencia_apelada","title":"Sentencia Apelada","order":3,"roman":"II"},
   {"key":"reparos_concretos","title":"Reparos Concretos","order":4,"roman":"III"},
   {"key":"sustentacion","title":"Sustentación","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones del Recurso","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 320-330 CGP',
 NULL,
 'Tribunal Superior / Consejo de Estado',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('recurso_queja:judicial:_:_', 'recurso_queja', 'civil',
 'judicial_recurso', 'procesal_judicial', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"hechos","title":"Hechos del Rechazo","order":2,"roman":"I"},
   {"key":"sustentacion","title":"Sustentación","order":3,"roman":"II"},
   {"key":"pretensiones","title":"Pretensiones","order":4,"roman":"III"},
   {"key":"firma","title":"Firma","order":5}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 352-354 CGP',
 NULL,
 'Superior del que negó',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('recurso_casacion:judicial:_:_', 'recurso_casacion', 'civil',
 'judicial_recurso', 'procesal_judicial', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_sentencia","title":"Sentencia Recurrida","order":2,"roman":"I"},
   {"key":"causales_casacion","title":"Causales Invocadas","order":3,"roman":"II"},
   {"key":"cargos","title":"Cargos Concretos","order":4,"roman":"III"},
   {"key":"sustentacion","title":"Sustentación","order":5,"roman":"IV"},
   {"key":"pretensiones","title":"Pretensiones","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 333-351 CGP',
 NULL,
 'Corte Suprema de Justicia',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- MEMORIALES (5 tipos)
-- ============================================================
('contestacion_demanda:judicial:_:_', 'contestacion_demanda', 'civil',
 'judicial_memorial', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, TRUE, TRUE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Identificación del Proceso","order":2,"roman":"I"},
   {"key":"pronunciamiento_hechos","title":"Pronunciamiento sobre los Hechos","order":3,"roman":"II"},
   {"key":"oposicion_pretensiones","title":"Oposición a las Pretensiones","order":4,"roman":"III"},
   {"key":"excepciones_previas","title":"Excepciones Previas","order":5,"roman":"IV"},
   {"key":"excepciones_merito","title":"Excepciones de Mérito","order":6,"roman":"V"},
   {"key":"fundamentos","title":"Fundamentos de la Defensa","order":7,"roman":"VI"},
   {"key":"pruebas","title":"Pruebas","order":8,"roman":"VII"},
   {"key":"anexos","title":"Anexos","order":9,"roman":"VIII"},
   {"key":"juramento","title":"Juramento","order":10,"roman":"IX"},
   {"key":"firma","title":"Firma","order":11}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 96-101 CGP',
 'Art. 206 CGP',
 'Mismo juez del proceso',
 '["CGP","CC"]'::jsonb, 'manual_seed_m19_24'),

('alegatos_conclusion:judicial:_:_', 'alegatos_conclusion', 'civil',
 'judicial_memorial', 'procesal_judicial', 'declarativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Proceso","order":2,"roman":"I"},
   {"key":"hechos_probados","title":"Hechos Probados","order":3,"roman":"II"},
   {"key":"analisis_pruebas","title":"Análisis Probatorio","order":4,"roman":"III"},
   {"key":"argumentos_juridicos","title":"Argumentos Jurídicos","order":5,"roman":"IV"},
   {"key":"conclusion","title":"Conclusión","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 373 CGP',
 NULL,
 'Mismo juez del proceso',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('solicitud_medidas_cautelares:judicial:_:_', 'solicitud_medidas_cautelares', 'civil',
 'judicial_memorial', 'procesal_judicial', 'petitorio',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 TRUE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Proceso","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"requisitos","title":"Requisitos (Fumus + Periculum)","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Medidas Solicitadas","order":5,"roman":"IV"},
   {"key":"caucion","title":"Caución Ofrecida","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 590-604 CGP',
 NULL,
 'Mismo juez del proceso',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('desistimiento:judicial:_:_', 'desistimiento', 'civil',
 'judicial_memorial', 'procesal_judicial', 'extintivo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Proceso","order":2,"roman":"I"},
   {"key":"manifestacion","title":"Manifestación de Desistimiento","order":3,"roman":"II"},
   {"key":"firma","title":"Firma","order":4}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 314-317 CGP',
 NULL,
 'Mismo juez',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

('aporte_documentos:judicial:_:_', 'aporte_documentos', 'civil',
 'judicial_memorial', 'procesal_judicial', 'informativo',
 'memorial_juzgado', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_proceso","title":"Proceso","order":2,"roman":"I"},
   {"key":"documentos_aportados","title":"Documentos Aportados","order":3,"roman":"II"},
   {"key":"manifestacion","title":"Manifestación","order":4,"roman":"III"},
   {"key":"firma","title":"Firma","order":5}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 244-265 CGP',
 NULL,
 'Mismo juez',
 '["CGP"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- CONTRATOS (10 tipos)
-- ============================================================
('contrato_arrendamiento_vivienda:civil:_:persona_natural', 'contrato_arrendamiento_vivienda', 'civil',
 'contractual_civil', 'sustantivo_civil', 'de_administracion',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes Contratantes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto","order":3},
   {"key":"canon","title":"SEGUNDA. Canon de Arrendamiento","order":4},
   {"key":"duracion","title":"TERCERA. Duración","order":5},
   {"key":"servicios","title":"CUARTA. Servicios Públicos","order":6},
   {"key":"obligaciones","title":"QUINTA. Obligaciones de las Partes","order":7},
   {"key":"causales_terminacion","title":"SEXTA. Causales de Terminación","order":8},
   {"key":"clausula_penal","title":"SÉPTIMA. Cláusula Penal","order":9},
   {"key":"otras_clausulas","title":"OTRAS CLÁUSULAS","order":10},
   {"key":"firma","title":"Firmas","order":11}
 ]'::jsonb,
 '{}'::jsonb,
 'Ley 820/2003 + Arts. 1973 ss. CC',
 NULL, NULL,
 '["CC","Ley 820/2003"]'::jsonb, 'manual_seed_m19_24'),

('contrato_arrendamiento_local_comercial:comercial:_:persona_juridica', 'contrato_arrendamiento_local_comercial', 'comercial',
 'contractual_mercantil', 'sustantivo_mercantil', 'de_administracion',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto","order":3},
   {"key":"canon","title":"SEGUNDA. Canon","order":4},
   {"key":"renovacion","title":"TERCERA. Renovación y Desahucio","order":5},
   {"key":"uso_destino","title":"CUARTA. Uso y Destinación","order":6},
   {"key":"obligaciones","title":"QUINTA. Obligaciones","order":7},
   {"key":"clausula_penal","title":"SEXTA. Cláusula Penal","order":8},
   {"key":"firma","title":"Firmas","order":9}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 518-524 CCo',
 NULL, NULL,
 '["CCo","CC"]'::jsonb, 'manual_seed_m19_24'),

('contrato_prestacion_servicios:civil:_:_', 'contrato_prestacion_servicios', 'civil',
 'contractual_civil', 'sustantivo_civil', 'de_compromiso',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto","order":3},
   {"key":"obligaciones_contratista","title":"SEGUNDA. Obligaciones del Contratista","order":4},
   {"key":"obligaciones_contratante","title":"TERCERA. Obligaciones del Contratante","order":5},
   {"key":"valor_forma_pago","title":"CUARTA. Valor y Forma de Pago","order":6},
   {"key":"duracion","title":"QUINTA. Duración","order":7},
   {"key":"causales_terminacion","title":"SEXTA. Causales de Terminación","order":8},
   {"key":"clausula_penal","title":"SÉPTIMA. Cláusula Penal","order":9},
   {"key":"naturaleza","title":"OCTAVA. Naturaleza Civil (no laboral)","order":10},
   {"key":"firma","title":"Firmas","order":11}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 2063-2069 CC',
 NULL, NULL,
 '["CC"]'::jsonb, 'manual_seed_m19_24'),

('contrato_compraventa_inmueble:civil:_:_', 'contrato_compraventa_inmueble', 'civil',
 'notarial_escritura', 'sustantivo_civil', 'de_disposicion',
 'instrumento_publico', 'firma_partes_notarial+diligencia_notarial', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"comparecientes","title":"Comparecientes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto - Identificación del Inmueble","order":3},
   {"key":"linderos_matricula","title":"SEGUNDA. Linderos y Matrícula Inmobiliaria","order":4},
   {"key":"precio_forma_pago","title":"TERCERA. Precio y Forma de Pago","order":5},
   {"key":"tradicion","title":"CUARTA. Tradición y Entrega","order":6},
   {"key":"saneamiento","title":"QUINTA. Saneamiento por Evicción y Vicios","order":7},
   {"key":"gravamenes","title":"SEXTA. Gravámenes y Cargas","order":8},
   {"key":"impuestos","title":"SÉPTIMA. Impuestos y Gastos","order":9},
   {"key":"otras_clausulas","title":"OTRAS","order":10},
   {"key":"firma","title":"Firmas","order":11},
   {"key":"diligencia_notarial","title":"Diligencia Notarial","order":12}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 1849-1954 CC + Decreto 960/1970',
 NULL, NULL,
 '["CC","Decreto 960/1970"]'::jsonb, 'manual_seed_m19_24'),

('contrato_trabajo_termino_fijo:laboral:_:persona_juridica', 'contrato_trabajo_termino_fijo', 'laboral',
 'contractual_laboral', 'laboral_sustantivo', 'de_compromiso',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Cargo y Funciones","order":3},
   {"key":"duracion","title":"SEGUNDA. Duración a Término Fijo","order":4},
   {"key":"salario","title":"TERCERA. Salario","order":5},
   {"key":"jornada","title":"CUARTA. Jornada de Trabajo","order":6},
   {"key":"lugar","title":"QUINTA. Lugar de Trabajo","order":7},
   {"key":"obligaciones","title":"SEXTA. Obligaciones","order":8},
   {"key":"prohibiciones","title":"SÉPTIMA. Prohibiciones","order":9},
   {"key":"justas_causas","title":"OCTAVA. Justas Causas de Terminación","order":10},
   {"key":"firma","title":"Firmas","order":11}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 45-46 CST',
 NULL, NULL,
 '["CST"]'::jsonb, 'manual_seed_m19_24'),

('contrato_trabajo_termino_indefinido:laboral:_:persona_juridica', 'contrato_trabajo_termino_indefinido', 'laboral',
 'contractual_laboral', 'laboral_sustantivo', 'de_compromiso',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Cargo y Funciones","order":3},
   {"key":"duracion","title":"SEGUNDA. Duración Indefinida","order":4},
   {"key":"salario","title":"TERCERA. Salario","order":5},
   {"key":"jornada","title":"CUARTA. Jornada","order":6},
   {"key":"periodo_prueba","title":"QUINTA. Período de Prueba","order":7},
   {"key":"obligaciones","title":"SEXTA. Obligaciones","order":8},
   {"key":"firma","title":"Firmas","order":9}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 47 CST',
 NULL, NULL,
 '["CST"]'::jsonb, 'manual_seed_m19_24'),

('contrato_mutuo:civil:_:_', 'contrato_mutuo', 'civil',
 'contractual_civil', 'sustantivo_civil', 'de_compromiso',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto - Suma Mutuada","order":3},
   {"key":"plazo","title":"SEGUNDA. Plazo","order":4},
   {"key":"intereses","title":"TERCERA. Intereses","order":5},
   {"key":"garantias","title":"CUARTA. Garantías","order":6},
   {"key":"clausula_penal","title":"QUINTA. Cláusula Penal y Mora","order":7},
   {"key":"firma","title":"Firmas","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 2221-2236 CC',
 NULL, NULL,
 '["CC"]'::jsonb, 'manual_seed_m19_24'),

('contrato_compraventa_vehiculo:comercial:_:_', 'contrato_compraventa_vehiculo', 'comercial',
 'contractual_mercantil', 'sustantivo_mercantil', 'de_disposicion',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"vehiculo","title":"PRIMERA. Identificación del Vehículo","order":3},
   {"key":"precio","title":"SEGUNDA. Precio","order":4},
   {"key":"entrega","title":"TERCERA. Entrega","order":5},
   {"key":"saneamiento","title":"CUARTA. Saneamiento","order":6},
   {"key":"traspaso","title":"QUINTA. Traspaso en RUNT","order":7},
   {"key":"firma","title":"Firmas","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'CCo + Decreto 19/2012',
 NULL, NULL,
 '["CCo","CC"]'::jsonb, 'manual_seed_m19_24'),

('contrato_confidencialidad_nda:comercial:_:_', 'contrato_confidencialidad_nda', 'comercial',
 'contractual_corporate', 'sustantivo_mercantil', 'de_compromiso',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto","order":3},
   {"key":"definicion_confidencial","title":"SEGUNDA. Definición de Información Confidencial","order":4},
   {"key":"obligaciones","title":"TERCERA. Obligaciones de Confidencialidad","order":5},
   {"key":"excepciones","title":"CUARTA. Excepciones","order":6},
   {"key":"duracion","title":"QUINTA. Duración","order":7},
   {"key":"penalidad","title":"SEXTA. Penalidad por Incumplimiento","order":8},
   {"key":"firma","title":"Firmas","order":9}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 1602 CC + Ley 256/1996',
 NULL, NULL,
 '["CC","CCo","Ley 256/1996"]'::jsonb, 'manual_seed_m19_24'),

('contrato_mandato:civil:_:_', 'contrato_mandato', 'civil',
 'contractual_civil', 'sustantivo_civil', 'de_mandato',
 'comparecencia_partes', 'firma_partes_contractuales', 'clausulas_ordinales',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"partes","title":"Partes","order":2},
   {"key":"objeto","title":"PRIMERA. Objeto del Mandato","order":3},
   {"key":"facultades","title":"SEGUNDA. Facultades del Mandatario","order":4},
   {"key":"obligaciones","title":"TERCERA. Obligaciones","order":5},
   {"key":"remuneracion","title":"CUARTA. Remuneración","order":6},
   {"key":"duracion","title":"QUINTA. Duración","order":7},
   {"key":"firma","title":"Firmas","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 2142-2199 CC',
 NULL, NULL,
 '["CC"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- CORPORATE — ESTATUTOS Y ACTAS (4 tipos)
-- ============================================================
('estatutos_sas:comercial:_:persona_juridica', 'estatutos_sas', 'comercial',
 'corporate_estatutos', 'sustantivo_mercantil', 'constitutivo',
 'estatutos_societarios', 'firma_partes_contractuales', 'articulado',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Acta de Constitución y Estatutos","order":1},
   {"key":"identificacion_accionistas","title":"Comparecencia de Accionistas","order":2},
   {"key":"capitulo_1","title":"Capítulo I. Disposiciones Generales","order":3},
   {"key":"capitulo_2","title":"Capítulo II. Capital y Acciones","order":4},
   {"key":"capitulo_3","title":"Capítulo III. Órganos Sociales","order":5},
   {"key":"capitulo_4","title":"Capítulo IV. Estados Financieros y Utilidades","order":6},
   {"key":"capitulo_5","title":"Capítulo V. Disolución y Liquidación","order":7},
   {"key":"firma","title":"Firmas","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'Ley 1258/2008',
 NULL, NULL,
 '["Ley 1258/2008","CCo"]'::jsonb, 'manual_seed_m19_24'),

('acta_asamblea_extraordinaria:comercial:_:persona_juridica', 'acta_asamblea_extraordinaria', 'comercial',
 'corporate_acta', 'sustantivo_mercantil', 'constitutivo',
 'acta_corporativa', 'firma_corporativa_organos', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"convocatoria","title":"Verificación de Convocatoria","order":2},
   {"key":"quorum","title":"Quórum","order":3},
   {"key":"orden_del_dia","title":"Orden del Día","order":4},
   {"key":"desarrollo","title":"Desarrollo de la Reunión","order":5},
   {"key":"decisiones","title":"Decisiones","order":6},
   {"key":"firma","title":"Firmas (Presidente y Secretario)","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 181-189 CCo',
 NULL, NULL,
 '["CCo","Ley 1258/2008"]'::jsonb, 'manual_seed_m19_24'),

('acta_junta_directiva:comercial:_:persona_juridica', 'acta_junta_directiva', 'comercial',
 'corporate_acta', 'sustantivo_mercantil', 'constitutivo',
 'acta_corporativa', 'firma_corporativa_organos', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"asistentes","title":"Asistentes","order":2},
   {"key":"quorum","title":"Quórum","order":3},
   {"key":"orden_del_dia","title":"Orden del Día","order":4},
   {"key":"decisiones","title":"Decisiones","order":5},
   {"key":"firma","title":"Firmas","order":6}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 432-438 CCo',
 NULL, NULL,
 '["CCo"]'::jsonb, 'manual_seed_m19_24'),

('reglamento_interno_trabajo:laboral:_:persona_juridica', 'reglamento_interno_trabajo', 'laboral',
 'corporate_policy', 'laboral_sustantivo', 'informativo',
 'politica_corporativa', 'firma_representante_legal', 'articulado',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_empresa","title":"Identificación de la Empresa","order":2},
   {"key":"capitulo_1","title":"Capítulo I. Condiciones de Admisión","order":3},
   {"key":"capitulo_2","title":"Capítulo II. Período de Prueba","order":4},
   {"key":"capitulo_3","title":"Capítulo III. Horarios y Jornada","order":5},
   {"key":"capitulo_4","title":"Capítulo IV. Días de Descanso","order":6},
   {"key":"capitulo_5","title":"Capítulo V. Salarios","order":7},
   {"key":"capitulo_6","title":"Capítulo VI. Prestaciones","order":8},
   {"key":"capitulo_7","title":"Capítulo VII. Obligaciones","order":9},
   {"key":"capitulo_8","title":"Capítulo VIII. Prohibiciones","order":10},
   {"key":"capitulo_9","title":"Capítulo IX. Régimen Disciplinario","order":11},
   {"key":"firma","title":"Firma del Representante Legal","order":12}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 104-125 CST',
 NULL, NULL,
 '["CST"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- PETITORIOS (5 tipos)
-- ============================================================
('derecho_peticion:admin:_:entidad_publica', 'derecho_peticion', 'admin',
 'petitorio_admin', 'administrativo_publico', 'petitorio',
 'carta_petitoria', 'firma_natural', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"peticionario","title":"Identificación del Peticionario","order":2},
   {"key":"entidad","title":"Entidad Destinataria","order":3},
   {"key":"hechos","title":"Hechos","order":4},
   {"key":"peticion_concreta","title":"Petición Concreta","order":5},
   {"key":"fundamentos","title":"Fundamentos","order":6},
   {"key":"notificaciones","title":"Datos de Notificación","order":7},
   {"key":"firma","title":"Firma","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 23 CN + Arts. 13-33 CPACA',
 NULL,
 NULL,
 '["CN","CPACA"]'::jsonb, 'manual_seed_m19_24'),

('derecho_peticion_informacion:admin:_:entidad_publica', 'derecho_peticion_informacion', 'admin',
 'petitorio_admin', 'administrativo_publico', 'petitorio',
 'carta_petitoria', 'firma_natural', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"peticionario","title":"Peticionario","order":2},
   {"key":"entidad","title":"Entidad","order":3},
   {"key":"informacion_solicitada","title":"Información Solicitada","order":4},
   {"key":"fundamentos","title":"Fundamentos","order":5},
   {"key":"notificaciones","title":"Notificaciones","order":6},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 74 CN + Ley 1712/2014 (Transparencia)',
 NULL, NULL,
 '["CN","CPACA","Ley 1712/2014"]'::jsonb, 'manual_seed_m19_24'),

('pqrs:admin:_:_', 'pqrs', 'admin',
 'petitorio_pqrs', 'administrativo_publico', 'petitorio',
 'carta_petitoria', 'firma_natural', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"solicitante","title":"Solicitante","order":2},
   {"key":"tipo_pqrs","title":"Tipo (P/Q/R/S)","order":3},
   {"key":"hechos","title":"Descripción de los Hechos","order":4},
   {"key":"peticion","title":"Petición","order":5},
   {"key":"firma","title":"Firma","order":6}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 23 CN + Ley 1755/2015',
 NULL, NULL,
 '["CN","CPACA","Ley 1755/2015"]'::jsonb, 'manual_seed_m19_24'),

('requerimiento_extrajudicial:civil:_:_', 'requerimiento_extrajudicial', 'civil',
 'petitorio_extrajudicial', 'sustantivo_civil', 'petitorio',
 'carta_petitoria', 'firma_natural', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"remitente","title":"Remitente","order":2},
   {"key":"destinatario","title":"Destinatario","order":3},
   {"key":"hechos","title":"Antecedentes","order":4},
   {"key":"requerimiento","title":"Requerimiento Concreto","order":5},
   {"key":"plazo","title":"Plazo Concedido","order":6},
   {"key":"consecuencias","title":"Consecuencias por Incumplimiento","order":7},
   {"key":"firma","title":"Firma","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 1610 ss. CC',
 NULL, NULL,
 '["CC","CCo"]'::jsonb, 'manual_seed_m19_24'),

('cobro_prejuridico:civil:_:_', 'cobro_prejuridico', 'civil',
 'petitorio_extrajudicial', 'sustantivo_civil', 'petitorio',
 'carta_petitoria', 'firma_natural', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"acreedor","title":"Acreedor","order":2},
   {"key":"deudor","title":"Deudor","order":3},
   {"key":"obligacion","title":"Obligación a Cobrar","order":4},
   {"key":"liquidacion","title":"Liquidación de la Deuda","order":5},
   {"key":"requerimiento","title":"Requerimiento de Pago","order":6},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 1602 + 1608 CC',
 NULL, NULL,
 '["CC"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- TRIBUTARIO (3 tipos)
-- ============================================================
('recurso_reconsideracion_dian:tributario:_:entidad_publica', 'recurso_reconsideracion_dian', 'tributario',
 'tributario_dian', 'tributario_dian', 'petitorio',
 'memorial_autoridad_admin', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_acto","title":"Acto Impugnado","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"sustentacion","title":"Sustentación","order":4,"roman":"III"},
   {"key":"pretensiones","title":"Pretensiones","order":5,"roman":"IV"},
   {"key":"pruebas","title":"Pruebas","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Arts. 720-722 ET',
 NULL, NULL,
 '["ET"]'::jsonb, 'manual_seed_m19_24'),

('solicitud_facilidad_pago_dian:tributario:_:entidad_publica', 'solicitud_facilidad_pago_dian', 'tributario',
 'tributario_dian', 'tributario_dian', 'petitorio',
 'carta_petitoria', 'firma_apoderado_judicial', 'numerico_simple',
 FALSE, FALSE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"contribuyente","title":"Contribuyente","order":2},
   {"key":"deuda","title":"Deuda Objeto de Facilidad","order":3},
   {"key":"propuesta_pago","title":"Propuesta de Pago","order":4},
   {"key":"garantias","title":"Garantías Ofrecidas","order":5},
   {"key":"firma","title":"Firma","order":6}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 814 ET',
 NULL, NULL,
 '["ET"]'::jsonb, 'manual_seed_m19_24'),

('respuesta_requerimiento_dian:tributario:_:entidad_publica', 'respuesta_requerimiento_dian', 'tributario',
 'tributario_dian', 'tributario_dian', 'declarativo',
 'memorial_autoridad_admin', 'firma_apoderado_judicial', 'romana_secciones',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"identificacion_requerimiento","title":"Requerimiento Respondido","order":2,"roman":"I"},
   {"key":"hechos","title":"Hechos","order":3,"roman":"II"},
   {"key":"respuesta_punto_a_punto","title":"Respuesta Detallada","order":4,"roman":"III"},
   {"key":"fundamentos","title":"Fundamentos","order":5,"roman":"IV"},
   {"key":"pruebas","title":"Pruebas","order":6,"roman":"V"},
   {"key":"firma","title":"Firma","order":7}
 ]'::jsonb,
 '{}'::jsonb,
 'Art. 707 ET',
 NULL, NULL,
 '["ET"]'::jsonb, 'manual_seed_m19_24'),

-- ============================================================
-- CONCEPTUAL (2 tipos)
-- ============================================================
('concepto_juridico:_:_:_', 'concepto_juridico', 'general',
 'conceptual', 'sustantivo_civil', 'informativo',
 'concepto_consultor', 'firma_consultor', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"consultante","title":"Consultante","order":2},
   {"key":"problema_juridico","title":"Problema Jurídico","order":3},
   {"key":"hechos_relevantes","title":"Hechos Relevantes","order":4},
   {"key":"marco_normativo","title":"Marco Normativo","order":5},
   {"key":"analisis","title":"Análisis Jurídico","order":6},
   {"key":"conclusiones","title":"Conclusiones","order":7},
   {"key":"recomendaciones","title":"Recomendaciones","order":8},
   {"key":"firma","title":"Firma del Consultor","order":9}
 ]'::jsonb,
 '{}'::jsonb,
 NULL,
 NULL, NULL,
 '[]'::jsonb, 'manual_seed_m19_24'),

('opinion_legal:_:_:_', 'opinion_legal', 'general',
 'conceptual', 'sustantivo_civil', 'informativo',
 'concepto_consultor', 'firma_consultor', 'numerico_simple',
 FALSE, TRUE, FALSE,
 '[
   {"key":"encabezado","title":"Encabezado","order":1},
   {"key":"consultante","title":"Consultante","order":2},
   {"key":"objeto_opinion","title":"Objeto de la Opinión","order":3},
   {"key":"antecedentes","title":"Antecedentes","order":4},
   {"key":"analisis","title":"Análisis","order":5},
   {"key":"opinion","title":"Opinión","order":6},
   {"key":"limitaciones","title":"Limitaciones","order":7},
   {"key":"firma","title":"Firma","order":8}
 ]'::jsonb,
 '{}'::jsonb,
 NULL,
 NULL, NULL,
 '[]'::jsonb, 'manual_seed_m19_24')

ON CONFLICT (structure_key) DO NOTHING;

COMMENT ON TABLE structure_recipes IS
  'M19.24.E: pre-seed con 50+ doc_types colombianos anchor.
   Cada uno tiene los 10 campos M19.24 (document_family, regimen_aplicable,
   naturaleza_acto, encabezado_tipo, cierre_tipo, numeracion_estilo,
   requires_*, playbooks). Discovery dinámico solo se invoca para combinaciones
   no pre-cargadas — para los conocidos es CACHE HIT desde día 1.';
