"""Block schema + SSE events para Document Generation v3.1."""
from lex.blocks.schema import (
    Run,
    Block,
    BlockType,
    TitleBlock,
    SectionHeadingBlock,
    SubsectionBlock,
    ParagraphBlock,
    HechoBlock,
    PretensionBlock,
    NormaCitadaBlock,
    JurisprudenciaBlock,
    SilogismoBlock,
    TableBlock,
    CalcStepBlock,
    ListItemBlock,
    JuramentoBlock,
    FirmaBlock,
    BlankBlock,
    new_block_id,
)
from lex.blocks.events import sse, SSEEvent

__all__ = [
    "Run",
    "Block",
    "BlockType",
    "TitleBlock",
    "SectionHeadingBlock",
    "SubsectionBlock",
    "ParagraphBlock",
    "HechoBlock",
    "PretensionBlock",
    "NormaCitadaBlock",
    "JurisprudenciaBlock",
    "SilogismoBlock",
    "TableBlock",
    "CalcStepBlock",
    "ListItemBlock",
    "JuramentoBlock",
    "FirmaBlock",
    "BlankBlock",
    "new_block_id",
    "sse",
    "SSEEvent",
]
